version: '3.8'

services:
  # 1. SQL Database Setup (MariaDB)
  mariadb:
    image: mariadb:10.6
    container_name: frappe-mariadb
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      - MYSQL_ROOT_PASSWORD=admin # Root password for MariaDB
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - frappe-network

  # 2. Redis Setup (Frappe ke liye zaroori hai)
  redis-cache:
    image: redis:alpine
    container_name: frappe-redis-cache
    restart: always
    networks:
      - frappe-network

  redis-queue:
    image: redis:alpine
    container_name: frappe-redis-queue
    restart: always
    networks:
      - frappe-network

  redis-socketio:
    image: redis:alpine
    container_name: frappe-redis-socketio
    restart: always
    networks:
      - frappe-network

  # 3. Frappe App Setup (Bench Development)
  frappe:
    image: frappe/bench:latest
    container_name: frappe-app
    restart: always

    command: bash /workspace/docker/init.sh
    environment:
      - SHELL=/bin/bash
    ports:
      - "8000:8000" # Frappe Web port
      - "9000:9000" # Socketio port
    volumes:
      - .:/workspace
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio
    networks:
      - frappe-network

volumes:
  mariadb-data:

networks:
  frappe-network:
    driver: bridge

